version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: diary-of-madao.postgres
    volumes:
      - "../blog-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - .env.database

  app:
    image: node:14
    container_name: diary-of-madao.app
    working_dir: /code
    command: >
      sh -c "./bin/wait-for-if.sh db:5432 -- npm install
      && npm run build
      && npm run migrate:prod
      && npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ".:/code"
      - "/home/blog/.ssh:/root/.ssh"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: diary-of-madao.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./.next:/usr/share/nginx/html/_next"
      - "/usr/local/nginx/cert:/usr/share/nginx/cert"
    depends_on:
      - app